import 'package:flutter/material.dart';
import '../../../auth/domain/entities/app_user.dart';
import '../models/notification_model.dart';

final List<NotificationData> hardcodedEventNotifications = [
  NotificationData(
    id: 'evt_1',
    type: NotificationType.event,
    appUser: AppUser(
      uid: 'sys',
      email: 'system@campus.edu',
      name: 'Campus Events',
      isOnline: true,
      isImageExists: false,
      imageURL: '',
    ),
    title: 'Tech Fest 2026 is happening this weekend',
    subtitle: 'Main Auditorium',
    description: 'Join us for 3 days of workshops, talks, and competitions.',
    timestamp: DateTime.now().subtract(const Duration(minutes: 45)),
    isRead: false,
    actionIcon: Icons.event_outlined,
    actionColor: const Color(0xFFFF9800),
    eventDate: DateTime.now().add(const Duration(days: 2)),
    eventMonth: 'JUL',
    eventLocation: 'Main Auditorium',
    reminderLabel: 'UPCOMING EVENT',
  ),
  NotificationData(
    id: 'evt_2',
    type: NotificationType.announcement,
    appUser: AppUser(
      uid: 'sys2',
      email: 'admin@campus.edu',
      name: 'Administration',
      isOnline: true,
      isImageExists: false,
      imageURL: '',
    ),
    title: 'New semester schedule has been released',
    subtitle: 'Academic Block',
    description: 'Check the updated timetable for all departments.',
    timestamp: DateTime.now().subtract(const Duration(hours: 4)),
    isRead: false,
    actionIcon: Icons.campaign_outlined,
    actionColor: const Color(0xFFFF9800),
    reminderLabel: 'ANNOUNCEMENT',
    eventLocation: 'All Departments',
  ),
  NotificationData(
    id: 'evt_3',
    type: NotificationType.event,
    appUser: AppUser(
      uid: 'sys3',
      email: 'sports@campus.edu',
      name: 'Sports Committee',
      isOnline: false,
      isImageExists: false,
      imageURL: '',
    ),
    title: 'Annual Sports Day registrations open',
    subtitle: 'Sports Complex',
    description: 'Register now for cricket, football, and athletics.',
    timestamp: DateTime.now().subtract(const Duration(hours: 8)),
    isRead: true,
    actionIcon: Icons.sports_soccer_outlined,
    actionColor: const Color(0xFF4CAF50),
    eventDate: DateTime.now().add(const Duration(days: 14)),
    eventMonth: 'AUG',
    eventLocation: 'Sports Complex',
    reminderLabel: 'UPCOMING EVENT',
  ),
  NotificationData(
    id: 'evt_4',
    type: NotificationType.announcement,
    appUser: AppUser(
      uid: 'sys4',
      email: 'lib@campus.edu',
      name: 'Library',
      isOnline: false,
      isImageExists: false,
      imageURL: '',
    ),
    title: 'Library hours extended for exam season',
    subtitle: 'Central Library',
    description: 'The library will remain open until 11 PM during finals.',
    timestamp: DateTime.now().subtract(const Duration(days: 1, hours: 3)),
    isRead: true,
    actionIcon: Icons.menu_book_outlined,
    actionColor: const Color(0xFF7C5CFA),
    reminderLabel: 'ANNOUNCEMENT',
    eventLocation: 'Central Library',
  ),
];
