import 'package:flutter/material.dart';
import '../../../auth/domain/entities/app_user.dart';
import '../models/notification_model.dart';

final List<NotificationData> hardcodedRequestNotifications = [
  NotificationData(
    id: 'req_1',
    type: NotificationType.requestChatPrivate,
    appUser: AppUser(
      uid: 'u1',
      email: 'priya@example.com',
      name: 'Priya Sharma',
      isOnline: true,
      isImageExists: false,
      imageURL: '',
    ),
    title: 'Priya Sharma wants to chat with you',
    subtitle: null,
    description: 'Hey! I wanted to discuss the upcoming project.',
    timestamp: DateTime.now().subtract(const Duration(minutes: 15)),
    isRead: false,
    actionIcon: Icons.chat_bubble_outline,
    actionColor: const Color(0xFF7C5CFA),
  ),
  NotificationData(
    id: 'req_2',
    type: NotificationType.requestChatGroup,
    appUser: AppUser(
      uid: 'u2',
      email: 'rahul@example.com',
      name: 'Rahul Verma',
      isOnline: false,
      isImageExists: true,
      imageURL: 'https://i.pravatar.cc/150?img=3',
    ),
    title: 'Rahul Verma invited you to group chat',
    subtitle: 'Design Team',
    description: 'Join the group to collaborate on the new UI.',
    timestamp: DateTime.now().subtract(const Duration(hours: 1)),
    isRead: false,
    actionIcon: Icons.group_outlined,
    actionColor: const Color(0xFF7C5CFA),
  ),
  NotificationData(
    id: 'req_3',
    type: NotificationType.requestChatPrivate,
    appUser: AppUser(
      uid: 'u3',
      email: 'anita@example.com',
      name: 'Anita Desai',
      isOnline: true,
      isImageExists: false,
      imageURL: '',
    ),
    title: 'Anita Desai wants to connect',
    subtitle: null,
    description: null,
    timestamp: DateTime.now().subtract(const Duration(hours: 3)),
    isRead: true,
    actionIcon: Icons.chat_bubble_outline,
    actionColor: const Color(0xFF7C5CFA),
  ),
  NotificationData(
    id: 'req_4',
    type: NotificationType.requestChatGroup,
    appUser: AppUser(
      uid: 'u4',
      email: 'vikram@example.com',
      name: 'Vikram Patel',
      isOnline: false,
      isImageExists: false,
      imageURL: '',
    ),
    title: 'Vikram Patel added you to',
    subtitle: 'Flutter Devs',
    description: 'Welcome to the Flutter Developers group!',
    timestamp: DateTime.now().subtract(const Duration(hours: 5)),
    isRead: true,
    actionIcon: Icons.group_outlined,
    actionColor: const Color(0xFF7C5CFA),
  ),
];
