import 'package:flutter/material.dart';
import '../../../auth/domain/entities/app_user.dart';
import '../models/notification_model.dart';

final List<NotificationData> hardcodedSocialNotifications = [
  NotificationData(
    id: 'soc_1',
    type: NotificationType.postCommented,
    appUser: AppUser(
      uid: 'u5',
      email: 'meera@example.com',
      name: 'Meera Nair',
      isOnline: true,
      isImageExists: false,
      imageURL: '',
    ),
    title: 'commented on your post',
    subtitle: 'Computer Science',
    description: 'Great insights on the AI workshop! Would love to join next time.',
    timestamp: DateTime.now().subtract(const Duration(minutes: 30)),
    isRead: false,
    actionIcon: Icons.comment_outlined,
    actionColor: const Color(0xFF4CAF50),
  ),
  NotificationData(
    id: 'soc_2',
    type: NotificationType.postCommented,
    appUser: AppUser(
      uid: 'u6',
      email: 'arjun@example.com',
      name: 'Arjun Mehta',
      isOnline: false,
      isImageExists: true,
      imageURL: 'https://i.pravatar.cc/150?img=7',
    ),
    title: 'liked your post',
    subtitle: null,
    description: null,
    timestamp: DateTime.now().subtract(const Duration(hours: 2)),
    isRead: false,
    actionIcon: Icons.favorite_outline,
    actionColor: const Color(0xFFE91E63),
  ),
  NotificationData(
    id: 'soc_3',
    type: NotificationType.postCommented,
    appUser: AppUser(
      uid: 'u7',
      email: 'sneha@example.com',
      name: 'Sneha Kapoor',
      isOnline: true,
      isImageExists: false,
      imageURL: '',
    ),
    title: 'replied to your comment',
    subtitle: 'Events',
    description: 'Totally agree! The hackathon was amazing.',
    timestamp: DateTime.now().subtract(const Duration(hours: 6)),
    isRead: true,
    actionIcon: Icons.reply_outlined,
    actionColor: const Color(0xFF2196F3),
  ),
  NotificationData(
    id: 'soc_4',
    type: NotificationType.postCommented,
    appUser: AppUser(
      uid: 'u8',
      email: 'karan@example.com',
      name: 'Karan Singh',
      isOnline: false,
      isImageExists: false,
      imageURL: '',
    ),
    title: 'mentioned you in a post',
    subtitle: 'Photography Club',
    description: 'Check out these campus shots!',
    timestamp: DateTime.now().subtract(const Duration(days: 1, hours: 2)),
    isRead: true,
    actionIcon: Icons.alternate_email,
    actionColor: const Color(0xFFFF9800),
  ),
];
