// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4XwFGNincdsqD2-k_ehkcU6A7ES2AX2g',
    appId: '1:644272384822:android:f0675f8dfa9771e466e197',
    messagingSenderId: '644272384822',
    projectId: 'studcom-53705',
    storageBucket: 'studcom-53705.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo0UHcISZ8N2RDeG0Ohub9ExPGDVkR1T8',
    appId: '1:644272384822:ios:4d37fddab8477c3866e197',
    messagingSenderId: '644272384822',
    projectId: 'studcom-53705',
    storageBucket: 'studcom-53705.firebasestorage.app',
    iosBundleId: 'com.example.noteswap',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo0UHcISZ8N2RDeG0Ohub9ExPGDVkR1T8',
    appId: '1:644272384822:ios:4d37fddab8477c3866e197',
    messagingSenderId: '644272384822',
    projectId: 'studcom-53705',
    storageBucket: 'studcom-53705.firebasestorage.app',
    iosBundleId: 'com.example.noteswap',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYH95OfoDdeMPuXrKs3PTjymiqYxZbil4',
    appId: '1:644272384822:web:7990a4790cf4e7d066e197',
    messagingSenderId: '644272384822',
    projectId: 'studcom-53705',
    authDomain: 'studcom-53705.firebaseapp.com',
    storageBucket: 'studcom-53705.firebasestorage.app',
    measurementId: 'G-R1JV6SG979',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYH95OfoDdeMPuXrKs3PTjymiqYxZbil4',
    appId: '1:644272384822:web:3e39a117a728574f66e197',
    messagingSenderId: '644272384822',
    projectId: 'studcom-53705',
    authDomain: 'studcom-53705.firebaseapp.com',
    storageBucket: 'studcom-53705.firebasestorage.app',
    measurementId: 'G-53571V1FLD',
  );
}
